service:
  name: image-rasize

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

custom:
  webpack:
    packager: yarn

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
