service:
  name: image-resize

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1 # Lambda@Edge restriction
  runtime: nodejs8.10 # Lambda@Edge restriction

custom:
  webpack:
    packager: yarn
    includeModules:
      forceInclude:
        - sharp # for native Node.js Add-on

functions:
  OriginResponse:
    handler: handler.originResponse
