service:
  name: image-resize

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1 # Lambda@Edge restriction
  runtime: nodejs10.x # Lambda@Edge restriction

layers:
  sharp:
    path: layers/sharp # for native Node.js Add-on

custom:
  webpack:
    packager: yarn
    includeModules:
      forceExclude:
        - sharp # included in the layer

functions:
  OriginResponse:
    handler: handler.originResponse
    layers:
      - Ref: SharpLambdaLayer
