service:
  name: image-rasize

plugins:
  - serverless-webpack

provider:
  name: aws
  region: us-east-1 # Lambda@Edge restriction
  runtime: nodejs8.10 # Lambda@Edge restriction

custom:
  webpack:
    packager: yarn

functions:
  OriginResponse:
    handler: handler.originResponse
